### ISSUE TITLE
Close menu on element click

### ISSUE THREAD

**Issue by patrickreeder** [vinnymoreira/stellarnav#10]
Hi,

At first I would like to thank you for the awesome work on the Stellarnav Menu! I really like it and use it on some websites.

There is only one thing that is giving me a hard time. I would like the responsive menu to close automatically whenever an menu item is clicked. In my usecase I have some links in the menu that direct the user to a section further down on the same page. Therefore the Menu should disappear when a link is clicked.

I am very thankfull for any advice on how to achieve this. Thanks!

**Comment by vinnymoreira** [comment]
Hi Patrick, 

Thanks for using Stellarnav. I'm glad to hear you like it. Here's a way to make any element close the nav on click:

```
<a href="#" id="close-nav">Close nav button</a>

jQuery('#close-nav').click(function() {
	var nav = $('.stellarnav');
	nav.removeClass('active');
	if( nav.hasClass('left right') ) {
		nav.find('ul:first').stop(true, true).fadeToggle(250);
	} else {
		nav.find('ul:first').stop(true, true).slideUp(250).toggleClass('active');
	}
});
```

I will add a 'close nav' method to the next version of the Stellarnav to make it easy for anyone who's trying to accomplish the same as you.

Thanks!
