### ISSUE TITLE
use of deprecated methods (jquery 3.0+) in stellarnav

### ISSUE THREAD

**Issue by Holger-S** [vinnymoreira/stellarnav#11]
Excerpt of browser console using jquery-migrate plugin:

JQMIGRATE: Migrate is installed with logging active, version 3.0.1 jquery-migrate-3.0.1.js:48:2

JQMIGRATE: jQuery.fn.bind() is deprecated
JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
JQMIGRATE: jQuery.fn.unbind() is deprecated

A fix would be nice :)
Cheers, Holger

**Comment by vinnymoreira** [comment]
Hi Holger,

Thanks for using Stellarnav and for pointing that out. That's been fixed in the latest version. 

Cheers!

Vinny
