### ISSUE TITLE
Additional language specific settings

### ISSUE THREAD

**Issue by Holger-S** [vinnymoreira/stellarnav#12]
Some time ago I've adapted version 1.2.0 to German strings as needed.
I've done this again for the latest stellarnav version, see attached diff file.

I'd like to encourage you to add settings for these strings in order to have a kind of internationalization of your script. Same way you already did for menuLabel = '' in version 2.5.0.
This way, anybody could permanently override the English standard strings with their own strings as needed, updates on the users side could be done without any further actions.

What'd you say?

[stellarnav_patch_de.txt](https://github.com/vinnymoreira/stellarnav/files/2585538/stellarnav_patch_de.txt)

**Comment by vinnymoreira** [comment]
Yes, totally! Thanks for your suggestion. I just added those options (locationLabel, phoneLabel, closeLabel) please refer to the docs. 

Thank you!
