### ISSUE TITLE
still use of deprecated methods (jquery 3.0+) in stellarnav 2.5.0

### ISSUE THREAD

**Issue by Holger-S** [vinnymoreira/stellarnav#14]
Hi Vinny,

thx for the latest!
Unfortunately there is one line left with deprecated method bind, so jquery-migrate plugin (3.0+) is still necessary with stellarnav version 2.5.0. See console log below.

```
console.trace() jquery-migrate-3.0.1.js:78:5
	migrateWarn /jquery/jquery-migrate-3.0.1.js:78:5
	bind /jquery/jquery-migrate-3.0.1.js:499:3
	$.fn.stellarNav/< /jquery/stellarnav.js:80:16
	each /jquery/jquery.min.js:2:2571
	each /jquery/jquery.min.js:2:1238
	$.fn.stellarNav /jquery/stellarnav.js:31:10
```

Pls have a look into my other opened issue.

Thx again!
Holger

P.S.: I've fixed it myself (.bind => .on) but anyways...

**Comment by vinnymoreira** [comment]
Thanks for pointing that out. That's been done in the new version.
