### ISSUE TITLE
Can't Make New Sub-Menu

### ISSUE THREAD

**Issue by Helpmetoday** [vinnymoreira/stellarnav#15]
Hello Vinny,

I have the following menu code and is working, but I want to add a new drop down, meaning I am trying to add a list tag with a link that will drop down and show more links. It should be displayed similar to that of the welcome menu, (https://www.worldclassads.com/classifieds/united-states/) but it will contain links, not a login form. Can you adjust the code below so that can be possible? The link will be for translation that I will add the languages into myself.

Note: When I tried to do it, I have added just above the closing div </div> tag the following: 

`<ul>`
`<li><a href="#">Translate:</a>`
`<li><a href="#">French</a>`
`<li><a href="#">Spanish</a>`
`<li><a href="#">Italian</a>`
`</li></ul>`
-------------------------------------------------------
My Original Menu Below: 
-------------------------------------------------------
`<div id="main-nav" class="stellarnav">`
`<ul>`
`{if $isLogin}`
`<li style="background-color: #000" class="welcome"><a href="#"><i class="fa fas fa-user-plus fa-lg"></i>&nbsp;{$lang.welcome}, {$isLogin}!</a>{include file='menus/account_menu.tpl'}`

`{else}`
`<li style="background-color: #000" class="welcome"><a href="#"><i class="fa fas fa-user-plus fa-lg"></i>&nbsp;{$lang.welcome} Visitor!{/if}</a>`

`<ul>`
`{include file='menus/account_menu.tpl'}`
`</li></ul>`

`<li><a href="about-us.html"><i class="fa fa-info-circle fa-lg"></i>&nbsp;About Us</a></li>`
`<li><a href="contact-us.html"><i class="fa far fa-envelope fa-lg"></i>&nbsp;Contact Us</a></li>`
`<li><a href="help.html"><i class="fa far fa-question-circle fa-lg"></i>&nbsp;Help</a></li>`
`<li><a href="add-listing.html"><i class="fa fas fa-newspaper-o fa-lg"></i>&nbsp;Post Listing</a></li>`

`</div>`

**Comment by vinnymoreira** [comment]
Hi Brian, 

This is not the place to get coding help. For technical coding issues please use https://stackoverflow.com/ you will also get help faster there.

Thank you!
