### ISSUE TITLE
Mobile Navigation Issue...

### ISSUE THREAD

**Issue by Helpmetoday** [vinnymoreira/stellarnav#16]
Hello Vinny,
When the StellarNav goes into mobile view, I seem to have changed something (or that I believe) to make the mobile version of the navigation menu appear as one div. I am not sure it is supposed to work that way, because, let's say for example, I wanted the mobile navigation menu work like the full sized (desktop) menu, and add a top margin (to lower) the drop down from the top part it seems this can't be done because the two parts of the menu are now attached. Can this be separated, in such a way that the desktop version of the menu currently displays?
Preview the navigation menu in both desktop (full size) and in mobile size by resizing browser window to see what I mean: 

https://www.worldclassads.com/classifieds/united-states/

Thank you
Brian

**Comment by vinnymoreira** [comment]
Hi Brian, 

For technical coding issues please use https://stackoverflow.com/ you will also get help faster there.

Thank you!
