### ISSUE TITLE
If submenu is out of viewport

### ISSUE THREAD

**Issue by elemis** [vinnymoreira/stellarnav#17]
If a submenu goes out of the viewport is it possible to change its position automatically so it opens on the left of the parent submenu instead of right side?

**Comment by sharathdaniel** [comment]
I'm having the same issue. One of my dropdown menu item is on the far right side of the page. Hovering it causes horizontal scrollbar on body.

**Comment by vinnymoreira** [comment]
Yes it is. Please refer to the "Extra" section on the documentation. There's a "drop-left" css class specifically for that. 

I hope that helps,

Vinny
