### ISSUE TITLE
Open and close dropdown on click

### ISSUE THREAD

**Issue by alexsamboy** [vinnymoreira/stellarnav#18]
Hello, the dropdown menu is currently displayed when I do mouse hover and I would like to display it when I click.

**Comment by vinnymoreira** [comment]
Hi Alex,

Thanks for using Stellarnav. As of now there isn't a way. Displaying the dropdown on hover is what differs Stellarnav from many other menus. However, I will keep that in mind and I might add that feature on future versions. 

Thank you!
