### ISSUE TITLE
Delay on mouse enter : new feature ?

### ISSUE THREAD

**Issue by webboy-fr** [vinnymoreira/stellarnav#2]
Hello ! Thank you for your plugin, i use it in one of my production web-site until few months.

I made a little modification to give a delay on the "mousenter" event (it was a "boss request" :) ).
Do you want to merge this feature to your official stellarnav plugin ?
For the moment, it's just hard-coded in my version of stellarnav. But I can easily add the delay option and improve the integration.

It's not in my habit to contribute in open source projects, so if I made something wrong, don't hesitate to tell me (starting to post that on an issue :-D ).

Let me up to date !

(Sorry for my english, I am French... I hope you didn't lost an eye reading me.)

**Comment by vinnymoreira** [comment]
Hi fyzalis,

Thanks for using Stellarnav! At the moment I intend to keep Stellarnav as simple and light as possible, but feel free to share what you did here and I will consider it in the future. Your English was great and you did nothing wrong. Thanks again! ;)
