### ISSUE TITLE
Activate submenu without clicking "+"

### ISSUE THREAD

**Issue by suscurio** [vinnymoreira/stellarnav#4]
Is it possible for the submenu to show by clicking the entire parent row/label? Currently the "+" must be clicked to show it. Would be nice if the entire row is clickable.

Also, would be possible to remove/change the word "Menu"?

**Comment by vinnymoreira** [comment]
Hi suscurio,

There are many menus in the market that already function that way. What makes Stellarnav unique is the ability to click on the parent menu. For instance, if you have an "About Us" page with content and it's a top level item on the nav, you would want users to be able to click on that page. Therefore it's important for the submenu to show only when clicked on the "+" button. 

To remove the word "menu", you can add this to your custom scripts:

`jQuery('.stellarnav.mobile .menu-toggle').text('').append('<i class="fa fa-bars"></i>');`

To change the word "menu" to "navigation" or something else you can use the same concept:

`jQuery('.stellarnav.mobile .menu-toggle').html('<i class="fa fa-bars"></i> Navigation');`

**Comment by smartcorestudio** [comment]
@suscurio if you need this behaviour, you can slightly modify stellarnav.js. Something like this:
```
		// adds toggle button to li items that have children
			nav.find('li a').each(function() {
				if ($(this).next().length > 0) {
					$(this).addClass('dd-toggler');
					$(this).parent('li').addClass('has-sub').append('<a class="dd-toggle dd-toggler" href="#"><i class="fa fa-plus"></i></a>');
				}
			});

			// expands the dropdown menu on each click 
			nav.find('li .dd-toggler').on('click', function(e) {
				e.preventDefault();
				e.stopPropagation();
				$(this).parent('li').toggleClass('hover');
				$(this).parent('li').children('ul').stop(true, true).slideToggle(250);
				$(this).parent('li').toggleClass('open');
			});
```

**Comment by den232** [comment]
Brilliant, @suscurio.   Just what I needed.    Incidentally, I double the suggestion that this be a top-level option!  Cheers jb
