### ISSUE TITLE
Occupy whole screen on click if menu is positioned right?

### ISSUE THREAD

**Issue by suscurio** [vinnymoreira/stellarnav#5]
Is it possible for the dropdown to occupy the whole screen (after clicking the menu) if the menu is positioned to the right?

Currently this is the behavior:
https://i.imgur.com/8wJKCcO.png

Can it be made to look like this?
https://i.imgur.com/fStvxON.png

Also, the word "Menu" is moving left with the dropdown when clicked (you can see in the first image the word "Menu" moves slightly to the left ). It would be nice if it sticks to its position.

**Comment by vinnymoreira** [comment]
Hi there, 

I don't recommend doing it for better UI purposes, but if you wish to do so you can simply add this to your stylesheet. 

`.stellarnav.mobile.right > ul, .stellarnav.mobile.left > ul { max-width: 100%; }`

Also, the screenshot is showing two menus in one page. This will cause conflicts between them. Try to just have one nav.
