### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by MIvanIsten** [vinnymoreira/stellarnav#6]
Demo is not working due:
"Mixed Content: The page at 'https://vinnymoreira.com/stellarnav-js-demo/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS."

**Comment by vinnymoreira** [comment]
Hi there,

Thanks for pointing that out! I have already fixed it and demo is working.
