### ISSUE TITLE
Adding Sub-menus...

### ISSUE THREAD

**Issue by Helpmetoday** [vinnymoreira/stellarnav#7]
Hello Vinny,

I have a quick question...I am having some difficulty in getting the sub-menus (ul levels) understood correctly...For example: I have a menu with static links on it such as Home -> About -> Contact...These menu items are perfect! I also have a link called Categories, inside the categories link I have sub-menus, and inside each sub-menu I have another level of sub-menus...How can I construct these levels once, and copy/paste the code for the new levels, or is that not possible to paste a level of lists and unordered lists? Another words, are each category level different, unable to use the same code?

I can only give you a general idea of my concept because the levels will be different, but let me give you this example which is based on my actual menu:

This menu level I have created ok:

Categories -> Clothing -> Men's Clothing -> Activewear -> Item1
Categories -> Clothing -> Men's Clothing -> Activewear -> Item2
Categories -> Clothing -> Men's Clothing -> Activewear -> Item3

But this one will give me a problem:

Categories -> Clothing -> Men's Clothing -> Activewear  (Then another category after Activewear, instead of an item)...I will have categories (or levels of different lengths, possibly, I will have only 3 category levels before the actual items (links) but likely more levels, so I need to know how to create the html code as in < ul > and < li > tags to accomplish this daunting task. I don't know if the cms I am using is causing the category levels to 'break' another words, by the first menu for example that I have created above, will break if I don't put a closing < /ul > tag, but the next menu I will add the closing < /ul > tag and it will be ok. I don't understand how the layout should be in terms of the < ul > and < li > tags.

Can you please send me a sample of code that can get me started with category levels of 3 levels of categories, then display items to see if it may be my cms that could be the culprit?

Thank you
Brian
Email: briangjester@yahoo.com

**Comment by vinnymoreira** [comment]
Hi Brian, 

Stellarnav supports up to 4-level deep dropdowns, so it should work for what you are trying to accomplish. Here's what it would like:

```html
<li><a href="#">Categories</a>
	<ul>
		<li><a href="#">Clothing</a>
			<ul>
				<li><a href="#">Men's Clothing</a>
					<ul>
						<li><a href="#">Activewear</a>
							<ul>
								<li><a href="#">Item1</a></li>
								<li><a href="#">Item2</a></li>
								<li><a href="#">Item3</a></li>
							</ul>
						</li>
					</ul>
				</li>
				<li><a href="#">Women's Clothing</a>
					<ul>
						<li><a href="#">Activewear</a>
							<ul>
								<li><a href="#">Item1</a></li>
								<li><a href="#">Item2</a></li>
								<li><a href="#">Item3</a></li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</li>
	</ul>
</li>
```
