### ISSUE TITLE
StellarNav Vertical Menu?

### ISSUE THREAD

**Issue by Helpmetoday** [vinnymoreira/stellarnav#9]
Hello,
Can you show me how to make stellarnav a vertical menu? I am currently using it as a horizontal menu, for a contact navigation, but I would also like to use it as a vertical menu if possible. I would appreciate all your effort in making that possible for me.

For example something like this would be great: https://www.jqueryscript.net/demo/Sticky-Sidebar-Navigation-Menu-with-jQuery-Vertical-Navigation/

But with StellarNav of course!

Thank you
Brian

**Comment by vinnymoreira** [comment]
Currently, there isn't a vertical version of Stellarnav. However, you can now add the `mobileMode` option and set it to `true`. That will convert the menu to mobile by default which it will be almost the same as having a vertical menu. You might have to make a few adjustments to the CSS to get the menu to display the way want it.

Thanks for suggesting that. I will keep that in mind for the next version. ;)

Vinny
